zuul:
  sensitive-headers:
  routes:
    myProduct:
      path: /myProduct/**
      serviceId: product
      sensitiveHeaders:
  ignored-patterns:
    - /**/product/listForOrder
management:
  security:
    enabled: false
ribbon:
  ReadTimeout: 5000
  SocketTimeout: 5000
spring:
  redis:
    host: 39.107.70.133
    port: 6379
